version: '3.1'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  www:
    build: .
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/10
    ports:
      - "8080:8080"
    depends_on:
      - redis